matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: PYTHON_ARCH="64" MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-7
    - os: osx
      language: generic
      env: PYTHON_ARCH="64" MATRIX_EVAL="CC=clang && CXX=clang++"
      # cache:
      #   directories:
      #     - $HOME/Library/Caches/Homebrew
      # before_cache:
      #   - brew cleanup
      # before_install:
      #   - brew update

before_install:
    - eval "${MATRIX_EVAL}"
    - export HELICS_VERSION="2.2.0"
    - if [[ $TRAVIS_OS_NAME == "windows" ]]; then choco install ninja; fi

install:
    - source "./scripts/install.sh"

script:
  # Your test script goes here
  - echo "script"

after_success:
  - source "./scripts/upload.sh"

notifications:
    email: false
